// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZHq744_BGsiCZ_6i2U-JgaCgJ_obLzDQ',
    appId: '1:115743573840:web:99e49191d27425befb8e55',
    messagingSenderId: '115743573840',
    projectId: 'dori-e3acb',
    authDomain: 'dori-e3acb.firebaseapp.com',
    storageBucket: 'dori-e3acb.appspot.com',
    measurementId: 'G-1MBVYEF5D2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE0dNTWwxYOl3E6nGEOpn6ZUrULJg3K0s',
    appId: '1:115743573840:android:20788cfe7ac1fc0ffb8e55',
    messagingSenderId: '115743573840',
    projectId: 'dori-e3acb',
    storageBucket: 'dori-e3acb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFQm2JUOBixlgTvIwCaYW3GftcVMEL8wg',
    appId: '1:115743573840:ios:757df2dcdd379fc3fb8e55',
    messagingSenderId: '115743573840',
    projectId: 'dori-e3acb',
    storageBucket: 'dori-e3acb.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFQm2JUOBixlgTvIwCaYW3GftcVMEL8wg',
    appId: '1:115743573840:ios:0d7ff509e76b013ffb8e55',
    messagingSenderId: '115743573840',
    projectId: 'dori-e3acb',
    storageBucket: 'dori-e3acb.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
